scripts = [
    "Arabic", "Armenian", "Bengali", "Canadian_Aboriginal", "Cherokee", "Cyrillic",
    "Devanagari", "Ethiopic", "Fraktur", "Georgian", "Greek", "Gujarati", "Gurmukhi",
    "HanS", "HanS_vert", "HanT", "HanT_vert", "Hangul", "Hangul_vert", "Hebrew",
    "Japanese", "Japanese_vert", "Kannada", "Khmer", "Lao", "Latin", "Malayalam",
    "Myanmar", "Oriya(Odia)", "Sinhala", "Syriac", "Tamil", "Telugu", "Thaana",
    "Thai", "Tibetan", "Vietnamese"
]

languages = [
    "chinese and english", "english", "french", "german", "japan", "korean",
    "chinese traditional", "Italian", "Spanish", "Portuguese", "Russia", "Ukranian",
    "Belarusian", "Telugu", "Saudi Arabia", "Tamil", "Afrikaans", "Azerbaijani",
    "Bosnian", "Czech", "Welsh", "Danish", "Maltese", "Dutch", "Norwegian", "Polish",
    "Romanian", "Slovak", "Slovenian", "Albanian", "Swedish", "Swahili", "Tagalog",
    "Turkish", "Uzbek", "Vietnamese", "Mongolian", "Abaza", "Arabic", "Hindi",
    "Uyghur", "Persian", "Urdu", "Serbian(latin)", "Occitan", "Marathi", "Nepali",
    "Serbian(cyrillic)", "Bulgarian", "Estonian", "Irish", "Croatian", "Hungarian",
    "Indonesian", "Icelandic", "Kurdish", "Lithuanian", "Latvian", "Maori", "Malay",
    "Adyghe", "Kabardian", "Avar", "Dargwa", "Ingush", "Lak", "Lezghian", "Tabassaran",
    "Bihari", "Maithili", "Angika", "Bhojpuri", "Magahi", "Nagpur", "Newari", "Goan Konkani"
]

language_symbols = [
    "ch", "en", "fr", "german", "japan", "korean", "ch_tra", "it", "es", "pt",
    "ru", "uk", "be", "te", "sa", "ta", "af", "az", "bs", "cs", "cy", "da", "mt",
    "nl", "no", "pl", "ro", "sk", "sl", "sq", "sv", "sw", "tl", "tr", "uz", "vi",
    "mn", "abq", "ar", "hi", "ug", "fa", "ur", "rs_latin", "oc", "mr", "ne",
    "rs_cyrillic", "bg", "et", "ga", "hr", "hu", "id", "is", "ku", "lt", "lv",
    "mi", "ms", "ady", "kbd", "ava", "dar", "inh", "lbe", "lez", "tab", "bh",
    "mai", "ang", "bho", "mah", "sck", "new", "gom"
]

script_language_map = {"chinese and english": "ch", "english": "en", "french": "fr", "german": "german", "japan": "japan", "korean": "korean", "chinese traditional": "ch_tra", "Italian": "it", "Spanish": "es", "Portuguese": "pt", "Russia": "ru", "Ukranian": "uk", "Belarusian": "be", "Telugu": "te", "Saudi Arabia": "sa", "Tamil": "ta", "Afrikaans": "af", "Azerbaijani": "az", "Bosnian": "bs", "Czech": "cs", "Welsh": "cy", "Danish": "da", "Maltese": "mt", "Dutch": "nl", "Norwegian": "no", "Polish": "pl", "Romanian": "ro", "Slovak": "sk", "Slovenian": "sl", "Albanian": "sq", "Swedish": "sv", "Swahili": "sw", "Tagalog": "tl", "Turkish": "tr", "Uzbek": "uz", "Vietnamese": "vi", "Mongolian": "mn", "Abaza": "abq", "Arabic": "ar", "Hindi": "hi", "Uyghur": "ug", "Persian": "fa", "Urdu": "ur", "Serbian(latin)": "rs_latin", "Occitan": "oc", "Marathi": "mr", "Nepali": "ne", "Serbian(cyrillic)": "rs_cyrillic", "Bulgarian": "bg", "Estonian": "et", "Irish": "ga", "Croatian": "hr", "Hungarian": "hu", "Indonesian": "id", "Icelandic": "is", "Kurdish": "ku", "Lithuanian": "lt", "Latvian": "lv", "Maori": "mi", "Malay": "ms", "Adyghe": "ady", "Kabardian": "kbd", "Avar": "ava", "Dargwa": "dar", "Ingush": "inh", "Lak": "lbe", "Lezghian": "lez", "Tabassaran": "tab", "Bihari": "bh", "Maithili": "mai", "Angika": "ang", "Bhojpuri": "bho", "Magahi": "mah", "Nagpur": "sck", "Newari": "new", "Goan Konkani": "gom"}
script_language_map_easyOCR = {
    "Abaza": "abq",
    "Adyghe": "ady",
    "Afrikaans": "af",
    "Angika": "ang",
    "Arabic": "ar",
    "Assamese": "as",
    "Avar": "ava",
    "Azerbaijani": "az",
    "Belarusian": "be",
    "Bulgarian": "bg",
    "Bihari": "bh",
    "Bhojpuri": "bho",
    "Bengali": "bn",
    "Bosnian": "bs",
    "Simplified Chinese": "ch_sim",
    "Traditional Chinese": "ch_tra",
    "Chechen": "che",
    "Czech": "cs",
    "Welsh": "cy",
    "Danish": "da",
    "Dargwa": "dar",
    "German": "de",
    "English": "en",
    "Spanish": "es",
    "Estonian": "et",
    "Persian (Farsi)": "fa",
    "French": "fr",
    "Irish": "ga",
    "Goan Konkani": "gom",
    "Hindi": "hi",
    "Croatian": "hr",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Ingush": "inh",
    "Icelandic": "is",
    "Italian": "it",
    "Japanese": "ja",
    "Kabardian": "kbd",
    "Kannada": "kn",
    "Korean": "ko",
    "Kurdish": "ku",
    "Latin": "la",
    "Lak": "lbe",
    "Lezghian": "lez",
    "Lithuanian": "lt",
    "Latvian": "lv",
    "Magahi": "mah",
    "Maithili": "mai",
    "Maori": "mi",
    "Mongolian": "mn",
    "Marathi": "mr",
    "Malay": "ms",
    "Maltese": "mt",
    "Nepali": "ne",
    "Newari": "new",
    "Dutch": "nl",
    "Norwegian": "no",
    "Occitan": "oc",
    "Pali": "pi",
    "Polish": "pl",
    "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Serbian (cyrillic)": "rs_cyrillic",
    "Serbian (latin)": "rs_latin",
    "Nagpuri": "sck",
    "Slovak": "sk",
    "Slovenian": "sl",
    "Albanian": "sq",
    "Swedish": "sv",
    "Swahili": "sw",
    "Tamil": "ta",
    "Tabassaran": "tab",
    "Telugu": "te",
    "Thai": "th",
    "Tajik": "tjk",
    "Tagalog": "tl",
    "Turkish": "tr",
    "Uyghur": "ug",
    "Ukranian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Vietnamese": "vi"
}

# script_language_map = {
#     "Arabic": ["Arabic", "Urdu", "Persian", "Uyghur", "Saudi Arabia"],
#     "Armenian": ["Armenian"],
#     "Bengali": ["Bengali"],
#     "Canadian_Aboriginal": ["Cree", "Inuktitut", "Ojibwe"],
#     "Cherokee": ["Cherokee"],
#     "Cyrillic": ["Russia", "Ukranian", "Belarusian", "Serbian(cyrillic)", "Bulgarian"],
#     "Devanagari": ["Hindi", "Marathi", "Nepali"],
#     "Ethiopic": ["Amharic"],
#     "Fraktur": ["german"],
#     "Georgian": ["Georgian"],
#     "Greek": ["Greek"],
#     "Gujarati": ["Gujarati"],
#     "Gurmukhi": ["Punjabi"],
#     "HanS": ["chinese and english"],
#     "HanS_vert": ["chinese and english"],
#     "HanT": ["chinese traditional"],
#     "HanT_vert": ["chinese traditional"],
#     "Hangul": ["korean"],
#     "Hangul_vert": ["korean"],
#     "Hebrew": ["Hebrew"],
#     "Japanese": ["japan"],
#     "Japanese_vert": ["japan"],
#     "Kannada": ["Kannada"],
#     "Khmer": ["Khmer"],
#     "Lao": ["Lao"],
#     "Latin": ["english", "french", "Spanish", "Portuguese", "Italian", "german", "Swedish", "Danish", "Dutch", "Norwegian", "Polish", "Romanian", "Czech", "Slovak", "Slovenian", "Albanian", "Welsh", "Irish", "Croatian", "Hungarian", "Indonesian", "Icelandic", "Lithuanian", "Latvian", "Maori", "Maltese", "Swahili", "Tagalog", "Turkish", "Uzbek", "Vietnamese", "Mongolian"],
#     "Malayalam": ["Malayalam"],
#     "Myanmar": ["Burmese"],
#     "Oriya(Odia)": ["Odia"],
#     "Sinhala": ["Sinhala"],
#     "Syriac": ["Syriac"],
#     "Tamil": ["Tamil"],
#     "Telugu": ["Telugu"],
#     "Thaana": ["Thaana"],
#     "Thai": ["Thai"],
#     "Tibetan": ["Tibetan"],
#     "Vietnamese": ["Vietnamese"]
# }
 
# # script_language_map = {
# #     "Arabic": ["ar", "ur", "fa", "ug", "sa"],
# #     # "Armenian": [],
# #     # "Bengali": [],
# #     "Canadian_Aboriginal": [],
# #     # "Cherokee": [],
# #     "Cyrillic": ["ru", "uk", "be", "rs_cyrillic", "bg"],
# #     "Devanagari": ["hi", "mr", "ne"],
# #     # "Ethiopic": [],
# #     "Fraktur": ["german"],
# #     # "Georgian": [],
# #     # "Greek": [],
# #     # "Gujarati": [],
# #     # "Gurmukhi": [],
# #     "HanS": ["ch"],
# #     "HanS_vert": ["ch"],
# #     "HanT": ["ch_tra"],
# #     "HanT_vert": ["ch_tra"],
# #     "Hangul": ["korean"],
# #     "Hangul_vert": ["korean"],
# #     # "Hebrew": [],
# #     "Japanese": ["japan"],
# #     "Japanese_vert": ["japan"],
# #     # "Kannada": [],
# #     # "Khmer": [],
# #     # "Lao": [],
# #     "Latin": ["en"],# "fr", "es", "pt", "it", "german", "sv", "da", "nl", "no", "pl", "ro", "cs", "sk", "sl", "sq", "cy", "ga", "hr", "hu", "id", "is", "lt", "lv", "mi", "mt", "sw", "tl", "tr", "uz", "vi", "mn"],
# #     # "Malayalam": [],
# #     # "Myanmar": [],
# #     # "Oriya(Odia)": [],
# #     # "Sinhala": [],
# #     # "Syriac": [],
# #     "Tamil": ["ta"],
# #     "Telugu": ["te"],
# #     # "Thaana": [],
# #     # "Thai": [],
# #     # "Tibetan": [],
# #     "Vietnamese": ["vi"]
# # }
 
# langs_tmp = {}
# for langs in languages:
#     # print(f"{script}: {", ".join(langs)}")
    
#         index = languages.index(langs)
#         langs_tmp[langs] = language_symbols[index]
#         # script_language_map[langs] = langs_tmp

# # # a=languages.index("Thaana")
# print(langs_tmp)
