training: 
  n_classes: 2387
  batch_size: 128

  # The initial learning rate to use for training.
  learning_rate: 0.01

  epochs: 40

  train_ratio: 0.7
  validation_ratio: 0.2
  test_ratio: 0.1

  # Save top k model: 
  k: 2